### ISSUE TITLE
Benign ReplicationGroup reconcilation errors

### ISSUE THREAD

**Issue by negz** [crossplaneio/stack-aws#46]
### What happened?

I noticed the following benign reconcile errors while trying out the new v1beta ReplicationGroup resource.

While creating:
```
    Last Transition Time:  2019-10-24T00:34:21Z
    Message:               cannot modify ElastiCache replication group: InvalidReplicationGroupState: Replication group must be in available state to modify.
                           status code: 400, request id: acf70fbf-1b09-4b26-8916-8b27f4817251
    Reason:                Encountered an error during managed resource reconciliation
    Status:                False
    Type:                  Synced
```

While deleting:
```
    Last Transition Time:  2019-10-24T00:48:22Z
    Message:               cannot delete ElastiCache replication group: InvalidReplicationGroupState: Replication group default-app-redis-dr2rp has status deleting which is not valid for deletion.
                           status code: 400, request id: b4d9f4d2-f278-4f5b-a837-514f23ad1cf5
    Reason:                Encountered an error during managed resource reconciliation
    Status:                False
    Type:                  Synced
```

These errors seem benign - the ReplicationGroup is created and then deleted just fine. We could probably avoid them by having the `ExternalClient` `Update` and `Delete` methods be no-op if the ReplicationGroup under reconciliation is observed to be creating or deleting.

Relates to https://github.com/crossplaneio/stack-aws/issues/30.

### How can we reproduce it?

Create and then delete a ReplicationGroup using the following claim and class:

```yaml
---
apiVersion: cache.aws.crossplane.io/v1beta1
kind: ReplicationGroupClass
metadata:
  name: aws-redis-standard
  labels:
    example: "true"
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  providerRef:
    name: example
  reclaimPolicy: Delete
  forProvider:
    replicationGroupDescription: "An example replication group"
    applyModificationsImmediately: true
    engine: "redis"
    engineVersion: "3.2.4"
    cacheParameterGroupName: default.redis3.2.cluster.on
    cacheNodeType: cache.t2.micro
    automaticFailoverEnabled: true
    numNodeGroups: 2
    replicasPerNodeGroup: 2
---
apiVersion: cache.crossplane.io/v1alpha1
kind: RedisCluster
metadata:
  name: app-redis
spec:
  classSelector:
    matchLabels:
      example: "true"
  writeConnectionSecretToRef:
    name: redissecret
  engineVersion: "3.2"
```

### What environment did it happen in?
Crossplane version:
